import Benefits from '@/components/benefits';
import Features from '@/components/features';
import Hero from '@/components/hero';
import How from '@/components/how';
import Partners from '@/components/partners';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Zeeh Interview Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Partners />
        <Features />
        <Benefits />
        <How />
      </main>
    </>
  );
}
