import API from '@/components/api';
import Benefits from '@/components/benefits';
import Features from '@/components/features';
import Footer from '@/components/footer';
import Hero from '@/components/hero';
import How from '@/components/how';
import Partners from '@/components/partners';
import Video from '@/components/video';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Zeeh Interview Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Hero />
        <Partners />
        <Features />
        <Benefits />
        <How />
        <Video />
        <API />
      </main>
      <Footer />
    </>
  );
}
